obj-$(CONFIG_TKERNEL) += base.o
obj-$(CONFIG_TKERNEL_NONPRIV_NETBIND) += netbind.o
obj-$(CONFIG_TKERNEL_TTOOLS) += ttools/
obj-$(CONFIG_TKERNEL_NETATOP) += netatop/
obj-$(CONFIG_TKERNEL_SHIELD_MOUNTS) += shield_mounts.o
